# Generated by Django 5.0.6 on 2024-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_item_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="items",
            field=models.ManyToManyField(blank=True, to="main.item"),
        ),
    ]
