# Generated by Django 5.0.6 on 2024-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_student_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="xp_required",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
