# Generated by Django 5.0.6 on 2024-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_item_xp_required_alter_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(default=False, upload_to="images/"),
        ),
    ]
