# Generated by Django 5.0.6 on 2024-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_student_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.ImageField(
                blank=True, default=False, null=True, upload_to="images/"
            ),
        ),
    ]
