# Generated by Django 5.0.6 on 2024-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionPedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulos",
            name="precio",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
