# Generated by Django 5.0.6 on 2024-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionPedidos", "0002_articulos_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
