# Generated by Django 5.0.6 on 2024-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionPedidos", "0003_alter_clientes_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="direccion",
            field=models.CharField(max_length=50, verbose_name="La dirección"),
        ),
    ]
