# Generated by Django 5.0.6 on 2024-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="password",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
