# Generated by Django 5.0.6 on 2024-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_class_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
