# Generated by Django 5.0.6 on 2024-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_student_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(
                blank=True, default=False, null=True, upload_to="images/"
            ),
        ),
    ]
